language: java
jdk:
  - oraclejdk8
install: ./gradlew setupCI
script: ./gradlew build
sudo: false
branches:
  only:
    - 1.7.10

notifications:
 irc:
  channels:
   - "irc.esper.net#MonsterRealm "
  use_notice: true
  skip_join: true
  template:
   - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
   - "Change view : %{compare_url}"
   - "Build details : %{build_url}"